### ISSUE TITLE
Quanta Dice TODO

### ISSUE THREAD

**Issue by quocble** [quantadex/react_quantadex#168]
Maintaining a list of TODO to get Dice to completion.

- [x] Low QDEX Balance
- [x] Bet detail screen
- [x] Bet history , (my bets, everyone bets)
- [x] Clickable dropdown on balance
- [x] Toolbar (sound, max bet, keyboard shortcut)
- [x] Wallet page link
- [x] Menu for others stuff, and logout
- [x] minimum bet?
- [x] open graph image banner
- [x] Show dropdown icon in balance bar
- [x] update explorer - see http://explorer.quantadex.com/testnet/account/charlie operations

**Comment by quocble** [comment]
My bets is not clickable when I'm not logged in... Probably should show "Not logged in - Connect your wallet"

When i'm logged in with zero bet for first time, the my bets show progress wheel continously. Maybe, show.  No bets

**Comment by quocble** [comment]
Payout shows 1.00x when my settings show 1.449X?

**Comment by quocble** [comment]
![image](https://user-images.githubusercontent.com/696643/59137181-437f4200-893b-11e9-9efd-99939b0fbb08.png)
need to increase decimals

**Comment by quocble** [comment]
- [ ] New fees text
- [ ] potential Term of service
-

**Comment by quocble** [comment]
Completed
